export const LANDING_AUDIO_CAPTIONS = [
    { start: 12.92, end: 14.34, text: 'So then, beyond that,' },
    { start: 14.62, end: 17.94, text: 'we are absolutely fascinated with the whole principle of remembering.' },
    { start: 19.14, end: 22.52, text: "And so then, when there's some gathering of people," },
    { start: 22.52, end: 23.6, text: 'and we say,' },
    { start: 24.68, end: 26.04, text: 'well, this is a great day,' },
    { start: 26.1, end: 28.6, text: "what a wonderful picnic or whatever it is we're having." },
    { start: 28.6, end: 30.52, text: "It's pretty somebody didn't bring a camera." },
    { start: 32.28, end: 33.46, text: 'It should have been photographed.' },
    { start: 34.96, end: 37.34, text: 'Now, do you see that in this whole thing,' },
    { start: 37.78, end: 39.4, text: 'there is both a gain and a loss?' },
    { start: 43.2, end: 46.24, text: 'The one school of people are saying it should be photographed.' },
    { start: 47.18, end: 49.6, text: 'The other school of people are saying, let go of it.' },
    { start: 51.56, end: 52.82, text: 'When you go around,' },
    { start: 53.16, end: 56.36, text: 'we had so much experience of this in Japan because' },
    { start: 56.36, end: 62.1, text: 'all our students brought cameras and were constantly photographing things.' },
    { start: 62.38, end: 65.98, text: 'I had a camera and I was constantly photographing things,' },
    { start: 66.14, end: 67.84, text: 'but I felt that as long as I had a' },
    { start: 67.84, end: 72.42, text: 'camera with me, I was somehow distracted from actuality.' },
    { start: 73.9, end: 77.58, text: 'I had little box with which I went around grabbing life.' },
    { start: 80.38, end: 82.26, text: 'Of course, it was great to come back and look' },
    { start: 82.26, end: 85.5, text: 'at it in the form of photographs,' },
    { start: 85.86, end: 88.46, text: "but there's something about the photograph that is inferior to" },
    { start: 88.46, end: 91.68, text: 'the actual experience of the two photographing.' },
    { start: 94.44, end: 100.48, text: 'But there is an immense fascination in photography,' },
    { start: 101.1, end: 102.86, text: 'in painting, in reproducing.' },
    { start: 103.42, end: 104.9, text: 'And reproducing, you see,' },
    { start: 105.1, end: 107.68, text: 'is the same thing as sexuality. It is reproduction,' },
    { start: 108.74, end: 110.7, text: 'only in another way.' },
    { start: 113.4, end: 117.3, text: "Because it tells you you're there. You're alive." },
    { start: 117.7, end: 118.94, text: 'The thing bounces, it echoes.' },
    { start: 121.28, end: 124.26, text: 'So the duplicity in all this is,' },
    { start: 124.52, end: 129.66, text: "you see, one school of religious people says, let it all go, don't be attached." },
    { start: 130.42, end: 132.82, text: 'In other words, and they also say, live in the moment,' },
    { start: 133.4, end: 134.98, text: "like Krishnamurti's doctrine of," },
    { start: 135.32, end: 137.54, text: 'stop trying to remember everything.' },
    { start: 137.9, end: 140.46, text: 'You may need a kind of factual memory for your' },
    { start: 140.46, end: 142.54, text: 'name and address and a telephone number,' },
    { start: 142.74, end: 143.86, text: 'but there are things like that.' },
    { start: 143.86, end: 149.86, text: "But don't linger over memories and treasure memories and say," },
    { start: 150.26, end: 152.38, text: "well, I'm going to keep my girlfriend's lock of hair," },
    { start: 152.84, end: 154.5, text: "and I'll take it out every now and then and" },
    { start: 154.5, end: 155.74, text: 'look at it and feel wonderful.' },
    { start: 157.02, end: 163.88, text: "That's clinging to life because that memory has got you hooked. It holds you to the past," },
    { start: 164.38, end: 166.0, text: 'and it holds you to death.' },
    { start: 168.84, end: 171.08, text: "But then there's the other school of thought," },
    { start: 171.34, end: 172.28, text: 'you see, quite opposite,' },
    { start: 172.68, end: 177.94, text: 'which says, remember to remember. Hold on to it all. Get involved.' },
    { start: 179.6, end: 181.02, text: "Keep your girlfriend's hair." },
    { start: 182.4, end: 183.42, text: 'Keep all the photographs.' },
];
