-- SEED: Recommended Tags
-- Using `on conflict (slug) do nothing` requires unique constraint on 'slug' which we added in migration.
-- Note: User might not have run migration yet, so ensure unique index exists or use name.
-- 'hub_tags' has 'name' unique? Setup script said `name text unique`.
-- Our migration added `slug` unique.

-- 1. Insert FEATURED tags
insert into public.hub_tags (name, is_featured) values
('UX Design', true),
('UI Design', true),
('Product Design', true),
('Design Systems', true),
('Typography', true),
('Color Theory', true),
('Accessibility', true),
('Photography', true),
('Cinematography', true),
('Editing (Film)', true),
('Color Grading', true),
('Sound Design', true),
('Music Production', true),
('Creative Coding', true),
('Generative Art', true),
('Interactive Art', true),
('AI Tools', true),
('Prompting', true),
('Figma', true),
('Blender', true),
('After Effects', true),
('DaVinci Resolve', true),
('Ableton Live', true),
('Obsidian', true),
('User Research', true),
('Ethnography', true),
('Data Visualization', true),
('Portfolio', true),
('Freelancing', true),
('Inspiration', true)
on conflict (name) do update set is_featured = true;

-- 2. Insert ALL OTHER tags
insert into public.hub_tags (name) values
('Designer'), ('Artist'), ('Filmmaker'), ('Creative Technologist'),
('Article'), ('Book'), ('Podcast'), ('Podcasting'), ('Newsletter'),
('YouTube Video'), ('Interview'), ('Case Study'), ('Tutorial'),
('Course'), ('Workshop'), ('Template'), ('UI Kit'), ('Plugin'),
('Tool'), ('Repository'), ('Open Source'), ('Research Paper'),
('Community'), ('Event'), ('Film Festival'), ('Dataset'),
('Guide'), ('Checklist'), ('Cheatsheet'),
('Interaction Design'), ('Service Design'), ('Design Ops'),
('Information Architecture'), ('Visual Design'), ('Graphic Design'),
('Brand Design'), ('Identity Design'), ('Content Design'),
('Content Strategy'), ('Copywriting'), ('Editorial Design'),
('Motion Design'), ('Animation'), ('3D Design'), ('Illustration'),
('Icon Design'), ('Layout'), ('Grid Systems'), ('Responsive Design'),
('Web Design'), ('Mobile Design'), ('Prototyping'), ('Wireframing'),
('User Flows'), ('Usability'), ('Design Patterns'), ('UI Patterns'),
('Component Library'), ('Design Tokens'), ('Style Guides'),
('Design Leadership'), ('Product Designer'), ('UX Designer'),
('UI Designer'), ('Interaction Designer'), ('Service Designer'),
('Design Researcher'), ('UX Researcher'), ('Content Designer'),
('Design Systems Lead'), ('DesignOps Manager'), ('Graphic Designer'),
('Brand Designer'), ('Illustrator'), ('Motion Designer'),
('Animator'), ('3D Artist'), ('Creative Director'), ('Art Director'),
('Photographer'), ('Cinematographer'), ('Director'), ('Producer'),
('Editor'), ('Colorist'), ('VFX Artist'), ('Sound Designer'),
('Audio Engineer'), ('Music Producer'), ('Composer'),
('Creative Coder'), ('Frontend Developer'), ('Design Engineer'),
('No-Code Builder'), ('FigJam'), ('Sketch'), ('Framer'),
('Webflow'), ('Astro'), ('React'), ('Next.js'), ('TypeScript'),
('Tailwind CSS'), ('Three.js'), ('GSAP'), ('p5.js'),
('TouchDesigner'), ('Unity'), ('Unreal Engine'), ('Cinema 4D'),
('Adobe Photoshop'), ('Adobe Illustrator'), ('Adobe Lightroom'),
('Capture One'), ('Premiere Pro'), ('Final Cut Pro'), ('Logic Pro'),
('Pro Tools'), ('Notion'), ('Miro'), ('Jira'), ('Trello'),
('GitHub'), ('Google Drive'), ('Slack'), ('Generative AI'),
('ChatGPT'), ('Midjourney'), ('Stable Diffusion'), ('Runway'),
('AI Video'), ('AI Image'), ('AI Audio'), ('Machine Learning'),
('Ethics'), ('Bias'), ('Privacy'), ('Copyright'),
('UX Research'), ('Sociology'), ('Anthropology'), ('Psychology'),
('Behavioral Design'), ('Systems Thinking'), ('Critical Design'),
('Speculative Design'), ('User Interviews'), ('Surveys'),
('Usability Testing'), ('Heuristic Evaluation'), ('Card Sorting'),
('Tree Testing'), ('Diary Studies'), ('Journey Mapping'),
('Personas'), ('Jobs to be Done'), ('A/B Testing'), ('Analytics'),
('Literature Review'), ('Desk Research'), ('Information Design'),
('Street Photography'), ('Documentary'), ('Portrait Photography'),
('Landscape Photography'), ('Fashion Photography'), ('Product Photography'),
('Composition'), ('Lighting'), ('Camera Movement'), ('Storyboarding'),
('Screenwriting'), ('Directing (Film)'), ('Pre-production'),
('Production'), ('Post-production'), ('Sound Mixing'), ('VFX')
on conflict (name) do nothing;
