-- Create the table
CREATE TABLE IF NOT EXISTS technology_course_refined (
    "Technology" TEXT PRIMARY KEY,
    "Origin_Company_KeyPeople_Place_and_Year" TEXT,
    "Simple_Utility" TEXT,
    "Real_Life_Example" TEXT,
    "Intro_Video_or_Tutorial_Link" TEXT,
    "Key_Skills_Thought_Process" TEXT,
    "Real_World_Implementation" TEXT
);

-- Note: The following are just the provided 28 rows from the prompt sample.
-- You can continue inserting the remaining 61 rows using the same pattern.
-- Alternatively, use Supabase CSV import for the full dataset.

INSERT INTO technology_course_refined (
    "Technology", 
    "Origin_Company_KeyPeople_Place_and_Year", 
    "Simple_Utility", 
    "Real_Life_Example", 
    "Intro_Video_or_Tutorial_Link", 
    "Key_Skills_Thought_Process", 
    "Real_World_Implementation"
) VALUES 
('A-Frame', 'Developed by Mozilla’s VR team (USA) and later maintained by Supermedium and Google; initial release December 2015', 'Open-source JavaScript framework for building WebXR/VR scenes with HTML and Three.js.', 'Used in Mozilla Hubs to create immersive chat rooms.', 'https://www.youtube.com/watch?v=0c_yW5AJ9gY', 'Basic HTML, JavaScript and 3D concepts; think in entities and components to compose immersive scenes; analyze scene graph and performance.', 'Interactive VR websites, virtual exhibitions and education apps run directly in the browser.'),
('ActionScript 3', 'Adobe Systems (USA); evolved from Macromedia Flash; AS3 introduced with Flash Player 9 in 2006', 'Programming language used to build interactive Flash applications and games (now legacy).', 'Early browser games and interactive websites built in Flash.', 'https://www.youtube.com/watch?v=5lL4O9dxWhA', 'Object-oriented programming, event-driven logic; think in timelines, movie clips, and user interaction handlers.', 'Legacy maintenance or porting Flash projects into modern HTML5/JS equivalents.'),
('Adobe After Effects', 'Originally by CoSA (USA) in 1993; acquired by Adobe in 1994; key figures include David Simons and CoSA founders', 'Motion graphics and compositing software used for animation, VFX, and visual storytelling.', 'Used for title sequences, explainer animations, and composited VFX shots.', 'https://www.youtube.com/watch?v=HBKxBzG8G9E', 'Keyframing, easing, compositing, masking; think in layers and timing; plan motion beats and visual hierarchy.', 'Social campaigns, brand films, UI motion prototypes, and VFX for video production.'),
('Adobe Illustrator', 'Adobe Systems (USA); first released 1987; key figure: John Warnock (Adobe co-founder)', 'Vector design tool for creating scalable illustrations, icons, and typography.', 'Logo design systems and icon libraries for products.', 'https://www.youtube.com/watch?v=Ib8UBwu3yGA', 'Vector paths, bezier curves, shape building; think in scalable components and clean geometry.', 'Brand identity work, illustration assets, UI iconography, print and digital creative.'),
('Adobe Photoshop', 'Developed by Thomas and John Knoll (USA) in 1987–1988; acquired by Adobe in 1988; first release 1990', 'Raster image editing for compositing, retouching, and graphic creation.', 'Photo retouching and campaign key art composites.', 'https://www.youtube.com/watch?v=IyR_uYsRdPs', 'Layers, masks, selections, color correction; think non-destructively with adjustment layers and smart objects.', 'Marketing visuals, asset production, creative experimentation, mockups and image manipulation.'),
('AI Storyboarding (Midjourney / DALL·E)', 'Midjourney (USA) founded by David Holz (2021); DALL·E by OpenAI (USA) announced 2021; diffusion models popularized 2020s', 'Generate visual frames quickly to explore narrative beats, composition, and mood for video/ads.', 'Rapid moodboards and shot concepts for brand campaigns before production.', 'https://www.youtube.com/watch?v=opqQ0tWfJ4M', 'Prompt writing, art direction, iteration; think in shot language (lens, lighting, framing) and consistent style prompts.', 'Pre-production planning, creative exploration, and pitch decks with fast visual iteration.'),
('Android Studio', 'Google (USA); announced 2013; based on IntelliJ IDEA by JetBrains', 'Official IDE for Android app development with Kotlin/Java and debugging tools.', 'Building Android prototypes for product demos and experiments.', 'https://www.youtube.com/watch?v=F7B4vO1OQfg', 'Mobile UI architecture, Gradle builds, debugging; think componentized screens and device constraints.', 'Android apps, ARCore demos, mobile utilities and experimental prototypes.'),
('Arduino', 'Originated at Interaction Design Institute Ivrea (Italy) in 2005; key figures: Massimo Banzi, David Cuartielles, Tom Igoe, Gianluca Martino, David Mellis', 'Open-source electronics platform for building interactive hardware prototypes with microcontrollers.', 'Interactive installations with sensors and LEDs.', 'https://www.youtube.com/watch?v=fJWR7dBuc18', 'Basic circuits, microcontroller programming; think input→process→output loops and physical interaction design.', 'Prototyping IoT devices, interactive art, tangible interfaces for installations and demos.'),
('ARCore', 'Google (USA); announced 2017', 'Google’s SDK for building augmented reality experiences on Android devices.', 'AR try-on experiences or interactive product demos.', 'https://www.youtube.com/watch?v=DW7a9n7a5cM', '3D math basics, plane detection, anchors; think environment understanding and stable placement.', 'Retail AR previews, interactive learning overlays, branded AR activations.'),
('AutoDesk Maya', 'Originally by Alias Systems (Canada/USA); later acquired by Autodesk (USA) in 2005; first released 1998', '3D modeling, animation, and rendering software for character and environment production.', 'Character animation for film and game cinematics.', 'https://www.youtube.com/watch?v=IYQmHf4zKxU', 'Modeling, rigging, animation curves; think in 3D pipelines and scene optimization.', 'High-end 3D assets for film/TV, game production, product visualization.'),
('Babel', 'Created by Sebastian McKenzie (Australia) in 2014 as 6to5; renamed Babel in 2015; open-source community maintained', 'JavaScript compiler that transforms modern JS into backwards-compatible versions.', 'Using ESNext syntax while supporting older browsers in web apps.', 'https://www.youtube.com/watch?v=R1F6xM4q3vI', 'Tooling, build pipelines, JS syntax; think compatibility and modular builds.', 'Modern web development workflows, bundling, and code transpilation in production apps.'),
('Blender', 'Created by Ton Roosendaal (Netherlands) in 1994; Blender Foundation established 2002', 'Free, open-source 3D creation suite for modeling, animation, simulation, and rendering.', '3D motion graphics for product launches.', 'https://www.youtube.com/watch?v=TPrnSACiTJ4', '3D modeling, shading, lighting; think node-based materials and efficient workflows.', '3D assets for web/AR, animation for brand films, interactive 3D prototypes.'),
('C++', 'Developed by Bjarne Stroustrup at Bell Labs (USA) beginning 1979; first commercial release 1985', 'High-performance programming language used for systems, graphics, and game engines.', 'Core components of Unreal Engine and many rendering systems.', 'https://www.youtube.com/watch?v=vLnPwxZdW4Y', 'Memory management, OOP, performance profiling; think low-level optimization and safe resource handling.', 'Graphics engines, creative coding tools, realtime systems, performance-critical applications.'),
('Cinema 4D', 'Maxon (Germany); first released 1990; key figure: Maxon development team', '3D modeling and motion graphics software popular for design and broadcast.', 'Motion design for brand campaigns and product animations.', 'https://www.youtube.com/watch?v=Qw5Vh1w3fJc', '3D fundamentals, MoGraph, rendering; think procedural animation and design iteration.', 'Brand motion, explainer visuals, 3D social content, product renders.'),
('Cloud Functions', 'Google Cloud (USA); Cloud Functions announced 2017; serverless paradigm popularized mid-2010s', 'Serverless compute to run event-driven functions without managing servers.', 'Triggering image processing when a file uploads to cloud storage.', 'https://www.youtube.com/watch?v=ZK5j9jC9NWI', 'Event-driven architecture, cloud permissions; think small single-purpose functions and observability.', 'APIs, automation pipelines, background tasks, integration glue for creative tools.'),
('D3.js', 'Created by Mike Bostock (USA) in 2011 at Stanford; open-source community maintained', 'JavaScript library for creating interactive data visualizations using web standards (SVG, Canvas).', 'Interactive infographic for climate data storytelling.', 'https://www.youtube.com/watch?v=_8V5o2UHG0E', 'Data binding, SVG, scales; think declarative mapping from data → visuals and interaction.', 'Interactive dashboards, narrative visualizations, rich web data stories.'),
('Docker', 'Docker, Inc. (USA); launched 2013; founders include Solomon Hykes', 'Containerization platform to package and run applications consistently across environments.', 'Running a creative web app locally with identical dependencies as production.', 'https://www.youtube.com/watch?v=pTFZFxd4hOI', 'Containers, images, networking; think reproducible environments and minimal images.', 'Deploying creative tools, data pipelines, reproducible dev setups, scalable services.'),
('Figma', 'Figma, Inc. (USA); founded 2012 by Dylan Field and Evan Wallace; launched 2016', 'Collaborative interface design tool for UI/UX prototyping and design systems.', 'Building a design system and interactive prototype for a product.', 'https://www.youtube.com/watch?v=FTFaQWZBqQ8', 'Design systems, auto-layout, components; think reusable UI patterns and collaborative iteration.', 'Product design, rapid prototyping, handoff to dev with specs and components.'),
('Flutter', 'Google (USA); first announced 2015; Flutter 1.0 released 2018', 'Cross-platform UI toolkit for building native apps from a single Dart codebase.', 'Prototype a cross-platform experience for mobile and web demos.', 'https://www.youtube.com/watch?v=1gDhl4leEzA', 'Widget composition, state management; think reactive UI and performance constraints.', 'Mobile apps, rapid prototypes, interactive experiences on multiple platforms.'),
('Framer Motion', 'Developed by Framer (Netherlands/UK); Framer Motion released 2018; key contributors: Matt Perry and open-source community', 'Animation library for React to create smooth UI transitions and gesture-driven motion.', 'Swipeable card deck interaction in a web prototype.', 'https://www.youtube.com/watch?v=1vKiPwEYbyk', 'Animation principles, React components; think motion as feedback and use spring/easing intentionally.', 'Interactive UI, scroll/gesture animations, playful transitions for product experiences.'),
('GANs (Generative Adversarial Networks)', 'Introduced by Ian Goodfellow and colleagues (USA) in 2014 at Université de Montréal / Stanford collaborations', 'Machine learning framework for generating realistic images/data via generator vs discriminator training.', 'Style transfer and synthetic portrait generation experiments.', 'https://www.youtube.com/watch?v=8L11aMN5KY8', 'Deep learning basics, training stability; think adversarial objectives, dataset bias, and evaluation.', 'Creative generative visuals, synthetic datasets, experimental content creation pipelines.'),
('GCP (Google Cloud Platform)', 'Google (USA); Google Cloud Platform launched 2008–2011 era; expanded significantly mid-2010s', 'Suite of cloud services for compute, storage, AI, and data processing.', 'Hosting a web app and running ML inference for creative tools.', 'https://www.youtube.com/watch?v=IUU6OR8yHCk', 'Cloud architecture, IAM, scalability; think modular services and cost-aware design.', 'Deploying creative products, data pipelines, serverless backends, AI services.'),
('Git', 'Created by Linus Torvalds (Finland) in 2005 for Linux development; open source', 'Version control system to track code changes and collaborate safely.', 'Managing a team project’s codebase with branching and pull requests.', 'https://www.youtube.com/watch?v=8JJ101D3knE', 'Branching, merging, commit hygiene; think collaboration workflows and history clarity.', 'Any software project collaboration, CI/CD integration, artifact versioning.'),
('Google Earth Studio', 'Google (USA); Earth Studio launched publicly 2018', 'Web-based animation tool for creating Google Earth imagery animations.', 'Flyover animations in documentaries and brand explainers.', 'https://www.youtube.com/watch?v=7F7Up5kqY5U', 'Camera paths, timing, export pipeline; think geographic storytelling and smooth transitions.', 'Location-based storytelling, product explainers, event recaps with geographic context.'),
('Google Maps APIs', 'Google (USA); Google Maps launched 2005; APIs evolved mid-2000s onward', 'APIs for embedding maps, geocoding, routing, and location data into apps.', 'Interactive map-based storytelling experience with custom markers.', 'https://www.youtube.com/watch?v=Zxf1mnP5zcw', 'API integration, geospatial thinking; think user context and map UX clarity.', 'Location products, interactive experiences, data visualization overlays on maps.'),
('Google Street View', 'Google (USA); launched 2007', 'Panoramic street-level imagery platform used for navigation and exploration.', 'Interactive cultural tours using Street View imagery.', 'https://www.youtube.com/watch?v=2qKZQ7C2oF4', 'Spatial storytelling, embedding; think scene navigation and guiding attention.', 'Virtual tours, education experiences, cultural archives, location-based narratives.'),
('GraphQL', 'Developed internally at Facebook (USA) in 2012; released open source 2015', 'API query language allowing clients to request exactly the data they need.', 'Frontend requesting a single structured payload for a complex UI card.', 'https://www.youtube.com/watch?v=Y0lDGjwRYKw', 'Schema design, resolvers; think client-driven data needs and performance.', 'Efficient APIs for apps, content systems, and complex data-driven UIs.'),
('HTML5', 'Standardized by W3C/WHATWG; HTML5 milestone spec 2014; developed by global web standards community', 'Core markup language for structuring modern web content and media.', 'Interactive microsites with video, canvas, and semantic layout.', 'https://www.youtube.com/watch?v=qz0aGYrrlhU', 'Semantic markup, accessibility; think structure-first and progressive enhancement.', 'Websites, interactive experiences, content-driven applications.')
ON CONFLICT ("Technology") DO UPDATE SET
    "Origin_Company_KeyPeople_Place_and_Year" = EXCLUDED."Origin_Company_KeyPeople_Place_and_Year",
    "Simple_Utility" = EXCLUDED."Simple_Utility",
    "Real_Life_Example" = EXCLUDED."Real_Life_Example",
    "Intro_Video_or_Tutorial_Link" = EXCLUDED."Intro_Video_or_Tutorial_Link",
    "Key_Skills_Thought_Process" = EXCLUDED."Key_Skills_Thought_Process",
    "Real_World_Implementation" = EXCLUDED."Real_World_Implementation";
