-- 1. Insert Media Mentions
INSERT INTO media_mentions (title, publication, url, published_at, categories, image_url, published)
VALUES
    (
        'When Creative Minds Collide: XY’s "Show Me The Way" Music Video Is Visual Pleasure',
        'Homegrown',
        'https://homegrown.co.in/homegrown-explore/when-creative-minds-collide-xys-show-me-the-way-music-video-is-visual-pleasure',
        '2021-01-10', -- Estimated date based on context
        ARRAY['Press', 'Music Video'],
        'https://homegrown.co.in/public/uploads/articles/featured_image/5ff5a6873b2d6.jpg', -- Extracted or placeholder
        true
    ),
    (
        'Four roommates shot a music video in their Mumbai flat and it received a premiere on Vh1',
        'Edex Live',
        'https://www.edexlive.com/breaking/2021/Jan/05/four-roommates-shot-a-music-video-in-their-mumbai-flat-and-it-received-a-premiere-on-vh1-17053.html',
        '2021-01-05',
        ARRAY['Press', 'Interview'],
        'https://gumlet.assettype.com/newindianexpress%2Fimport%2F2021%2F1%2F5%2Foriginal%2F0906_XY_1_1.jpg', -- Placeholder/Guess
        true
    ),
    (
        'Watch Electronic Pop Duo XY’s Cinematic Video for Debut Single "Show Me The Way"',
        'Rolling Stone India',
        'https://rollingstoneindia.com/watch-electronic-pop-duo-xys-cinematic-video-for-debut-single-show-me-the-way/',
        '2021-01-07', -- Estimated
        ARRAY['Press', 'Featured'],
        'https://rollingstoneindia.com/wp-content/uploads/2021/01/XY-Show-Me-The-Way-960x639.jpg', -- Placeholder/Guess
        true
    );

-- 2. Create Awards Table
CREATE TABLE IF NOT EXISTS awards (
    id bigint generated by default as identity primary key,
    title text not null,
    category text,
    value text, -- text to allow currency symbols like £28,000
    date date,
    url text,
    description text,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Insert Apple Scholarship Award
INSERT INTO awards (title, category, value, date, url, description)
VALUES (
    'Apple Scholarship',
    'Higher Education',
    '£28,000',
    '2022-08-15',
    '/awards/apple-scholarship',
    'Full scholarship covering tuition for MA at Royal College of Art, London.'
);


-- 5. Insert Blog Post 2: Everything You Need to Know (Guide)
INSERT INTO blog (title, slug, excerpt, content, published_at, published, category, tags, cover_image)
VALUES (
    'Everything You Need to Know About Scholarships for Higher Studies in World''s best art and design colleges',
    'scholarships-for-higher-studies',
    'A comprehensive guide to scholarships for international students, including Aga Khan, Charles Wallace, and more.',
    E'Securing funding for higher education in art and design can be daunting, but there are numerous opportunities available for international students. Here is a curated list of scholarships and funding bodies to help you pursue your dreams.\n\n## Global & UK Specific Scholarships\n\n### Aga Khan Foundation’s International Scholarship Programme (AKF ISP)\nThe Aga Khan Foundation provides a limited number of scholarships each year for postgraduate studies to outstanding students from select developing countries who have no other means of financing their studies.\n\n### Charles Wallace India Trust Scholarships\nFor Indians to gain experience and deeper exposure to the arts and heritage conservation in the UK.\n\n### Commonwealth Master’s Scholarships\nFunded by the UK Foreign, Commonwealth & Development Office (FCDO), these scholarships enable talented and motivated individuals to gain the knowledge and skills required for sustainable development.\n\n### Inlaks Scholarships\nThe Inlaks Shivdasani Foundation offers scholarships for young Indians to take up higher studies at top-rated American, European, and UK institutions.\n\n## Other Notable Funds\n- **Education Future International Scholarship**: For Indian students studying abroad.\n- **JND TATA Endowment**: Loan scholarships for higher studies.\n- **Lady Meherbai D Tata Education Trust**: For Indian women graduates.\n- **KC Mahindra Trust Foundation**: Interest-free loan scholarships.\n- **The Narotam Sekhsaria Foundation**: Interest-free scholarship loans.\n- **National Overseas Scholarships**: Facilitated by the Ministry of Social Justice and Empowerment.\n\n## Search Portals\nThese platforms are excellent resources for finding tailored opportunities:\n- [MastersCompare](https://www.masterscompare.com)\n- [FindAMasters](https://www.findamasters.com)\n- [TopUniversities](https://www.topuniversities.com)\n- [Postgrad Solutions](https://www.postgrad.com)\n- [MastersPortal](https://www.mastersportal.com)\n- [Chevening Scholarships](https://www.chevening.org)\n- [Educations.com](https://www.educations.com)\n\n## My Journey\nI was fortunate enough to receive a full scholarship from Apple for my time at the RCA. It changed everything for me. You can read more about my personal experience here:\n\n[**How Apple Funded My Dream at RCA**](/blog/how-apple-funded-my-dream-at-rca)\n\nAnd check out my [Awards Page](/awards/apple-scholarship) for more details.',
    NOW(),
    true,
    ARRAY['Resources', 'Scholarships'],
    ARRAY['Funding', 'Masters', 'Study Abroad'],
    '/assets/neon-glow-box.png' -- Will create this asset or handle in code
);
