-- Create Education Table
CREATE TABLE IF NOT EXISTS education (
    id bigint generated by default as identity primary key,
    institution text not null,
    location text,
    degree text,
    course text,
    start_year text,
    end_year text,
    details text,
    specialization text,
    link_text text,
    link_url text,
    sort_order integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert Data
INSERT INTO education (institution, location, degree, course, start_year, end_year, details, specialization, link_text, link_url, sort_order)
VALUES
    (
        'Royal College of Art',
        'London',
        'M.A (Master of Arts)',
        'Digital Direction',
        '2022',
        '2023',
        'Translated my personal journey of love, grief, and healing into photographs, prints, writings, and performance films. Wrote a thesis, designed a photobook, and exhibited my work at the RCA Graduate Show 2023 in London.',
        'Explored the emotional pain of romantic rejection and the loss of a loved one, drawing parallels between both experiences and tracing how both wounds mirror each other.',
        'Link to a repository of all the research, photography works, films and writings.',
        '/photography', -- Assumption: linking to photography work
        1
    ),
    (
        'National Institute of Design',
        'Ahmedabad',
        'M.Des (Master of Design)',
        'Film and Video Communication',
        '2021',
        '2022',
        'Crafted short films and audio stories on anxiety, healing and mental health. Left NID after a year and moved to London for a fully funded masters at the Royal College of Art.',
        NULL,
        'Watch my films on mental health focused on navigating rejection anxiety, healing and therapy.',
        '/films', -- Assumption: linking to films page
        2
    ),
    (
        'National Institute of Technology',
        'Rourkela',
        '(B.Tech + M.Tech) Bachelor of Technology + Master of Technology',
        'Mechanical Engineering',
        '2012',
        '2017',
        'Made a film so compelling, the Tech Mahindra CMO wanted me on their brand team when I was 21.',
        'Specialised in Mechatronics and Automation during my masters and worked on aerial drone photography and photogrammetry. I was the president of the film-making club where I executed film-making workshops. Served as Festival Director for Roots, a student-led creative conference; led concept design, speaker outreach, and full event execution connecting students with industry professionals.',
        NULL,
        NULL,
        3
    );
