const researchProjects = [
  {
    id: "fallback-invisible-punctums",
    slug: "invisible-punctum",
    status: "wip",
    featuredOrder: 10,
    title: "Invisible Punctums",
    oneLineDescription: "An AI-driven exploration of human memory, data, and the gaps in our digital archives.",
    context: "",
    specificContribution: "",
    yearStart: 2026,
    yearEnd: null,
    workInProgress: true,
    limitedPublic: true,
    coverUrl: "https://jwipqbjxpmgyevfzpjjx.supabase.co/storage/v1/object/public/research/covers/1769636977430_msh94w5fk.jpg",
    coverAlt: "Invisible Punctums research project cover",
    taxonomies: [
      { groupType: "primary", label: "Research", slug: "research" },
      { groupType: "primary", label: "Technology", slug: "technology" },
      { groupType: "primary", label: "Experimental", slug: "experimental" },
      { groupType: "technology", label: "AI", slug: "ai" },
      { groupType: "theme", label: "Memory", slug: "memory" },
    ],
    organisations: [],
    collaborators: [],
    links: [{ linkType: "external", label: "Open the existing research project", url: "/research/invisible-punctum" }],
    blocks: [],
  },
  {
    id: "fallback-gesture-image-preview",
    slug: "gesture-image-preview",
    status: "wip",
    featuredOrder: 20,
    title: "Gesture Image Preview",
    oneLineDescription: "A hand-gesture-controlled card stack for previewing photographs as if they were physical cards, with a simple voice-trigger layer for sound-based interaction.",
    context: "",
    specificContribution: "",
    yearStart: 2026,
    yearEnd: null,
    workInProgress: true,
    limitedPublic: true,
    coverUrl: "https://assets.newatlas.com/dims4/default/83c8dc7/2147483647/strip/true/crop/1564x1043+0+19/resize/800x533!/format/webp/quality/90/?url=https%3A%2F%2Fnewatlas-brightspot.s3.amazonaws.com%2Farchive%2Fgest-1.jpg",
    coverAlt: "Hand gesture interface research reference image",
    taxonomies: [
      { groupType: "primary", label: "Research", slug: "research" },
      { groupType: "primary", label: "Technology", slug: "technology" },
      { groupType: "primary", label: "Photography", slug: "photography" },
      { groupType: "method", label: "Hand Tracking", slug: "hand-tracking" },
      { groupType: "genre", label: "Interaction Design", slug: "interaction-design" },
    ],
    organisations: [],
    collaborators: [],
    links: [{ linkType: "external", label: "Open the existing research project", url: "/research/gesture-image-preview" }],
    blocks: [],
  },
  {
    id: "fallback-polaroid-hub",
    slug: "polaroid-hub",
    status: "wip",
    featuredOrder: 30,
    title: "Polaroid Hub",
    oneLineDescription: "An interactive photo arrangement experiment - handle photographs like physical objects, sequence them on a digital table, and feel how their order changes meaning.",
    context: "",
    specificContribution: "",
    yearStart: 2026,
    yearEnd: null,
    workInProgress: true,
    limitedPublic: true,
    coverUrl: "https://jwipqbjxpmgyevfzpjjx.supabase.co/storage/v1/object/public/research/covers/1769637180128_m89jj2boy.jpg",
    coverAlt: "Polaroid Hub interactive photography project cover",
    taxonomies: [
      { groupType: "primary", label: "Creative", slug: "creative" },
      { groupType: "primary", label: "Research", slug: "research" },
      { groupType: "primary", label: "Photography", slug: "photography" },
      { groupType: "genre", label: "Interaction Design", slug: "interaction-design" },
    ],
    organisations: [],
    collaborators: [],
    links: [{ linkType: "external", label: "Open the existing research project", url: "/research/polaroid-hub" }],
    blocks: [],
  },
];

export const portfolioFallbackProjects = researchProjects;

