export const vaultTags = [
    "2025", "AEOS", "Apple", "Byung Chul Han", "Chris Do", "HER", "IMG_1984",
    "Immigrant", "Inspiration", "LLM", "MIT", "Money", "NID", "PLORK", "PhD",
    "Puri", "RAG", "RCA", "UK", "Varun Mayya", "Yashawinee", "abodid", "absence",
    "activism", "advertising", "aesthetic", "affirmation", "africa", "agency",
    "agentic ai", "ai filmmaking", "ai storytelling", "ai", "alexithymia",
    "alok menon", "ambition", "america", "analogy", "ancestor", "anger",
    "anhedonia", "ansel adams", "anthropology", "antigravity", "app ideas", "app",
    "application", "archive", "arnika ahldag", "art and technology", "art of living",
    "art therapy", "art world", "art", "artemis", "articles", "articulation",
    "artificial intelligence", "artist", "authenticity", "auto fiction",
    "autobiography", "autoethnography", "automation", "bahi re padiba", "beef",
    "belief", "best job description lines", "bhubaneswar", "birthday", "blog",
    "book in progress", "book recommendation", "book references", "book snippet",
    "book title", "book", "bookmarked websites", "books to buy", "branding",
    "bravery", "brene brown", "business", "cambridge", "capitalism", "career insights",
    "career tips", "career", "carlin 2021", "carolyn ellis", "caste", "chat gpt",
    "cheryl mukherji", "children", "city", "climate", "code", "collage",
    "colonisation", "comment", "communication", "competence", "completed writing pieces",
    "completed", "complicated grief", "computer vision", "computer", "concerts",
    "conde nast", "connection", "consciousness", "consent", "contemporary art",
    "contrast", "conversation", "coping mechanism", "copy references", "copyright",
    "corporate", "courage", "creative block", "creative director", "creative growth",
    "creative", "culture", "curated lists", "curation", "curiosity", "cv", "dance",
    "data", "dating", "death", "depression", "designer", "desire", "development",
    "diary", "digital", "discrimination", "documentation", "documents", "dream journal",
    "dream", "ecology", "economy", "edex", "editorial", "efficiency", "ego",
    "elevator pitch", "emotions", "essay", "ethics", "ethnography", "eudaimonia",
    "excavations", "exhibition", "famous", "feelings", "female body", "fhf",
    "fiction", "fictional elements", "figuring out", "file", "film and video communication",
    "film heritage foundation", "film reviews", "films", "final negotiation",
    "financial", "fine art", "first love", "fitness", "forget", "forgiveness",
    "frameless", "freedom", "friendship", "funding", "funeral", "future", "gardening",
    "gaze", "gelatin", "gender", "generalist", "generational wealth", "generative ai",
    "geo politics", "ghibli", "ghosting", "ghosts", "google creative lab", "google",
    "great work", "greek", "grief", "grope", "habits", "happiness", "healing",
    "health", "healthy habits", "heartbreak", "higher education", "homegrown",
    "hope", "human body", "human", "icloud", "idea", "ideas", "identity capital",
    "identity", "image processing", "image", "imagination", "immigration",
    "indian culture", "informational", "insight", "insta post", "installation",
    "interdisciplinary", "interviews", "intuition", "investment", "jillian turecki",
    "joan didion", "job description", "john berger", "jon flynn", "journal",
    "journalling", "juxtaposition", "karma", "knowledge", "learned meaninglessness",
    "learning methodology", "learning", "letting go", "life advice", "life",
    "lifestyle", "linkedin post", "list", "london", "long form", "longing",
    "loss", "love quote", "love", "magazine", "man's search for meaning",
    "manifestation", "map", "marriage", "married life", "matrimony", "media mentions",
    "meeting", "memoir", "memories", "memory", "mental health", "mentorship",
    "met museum", "metaphor", "michelangelo", "mind", "miss", "missing", "mistakes",
    "mother", "mourning", "movies", "mumbai", "music band", "my thoughts", "mystery",
    "myth", "narcissism", "narrative", "necromancy", "neil patel", "nervous system",
    "new video ideas", "new york", "newsletter", "nora kennedy", "nostalgia",
    "notebook", "notes from articles", "notetaking", "objects", "obsidian", "ongoing",
    "online article", "online blogs", "open ai", "opinion", "organism", "outernet",
    "ownership", "pain", "paint", "painting", "paper based", "parents", "patriarchy",
    "performance art", "performance art", "performance", "personal project",
    "personal website", "personal", "philosophy", "photo", "photobook", "photography",
    "phototherapy", "pitch", "poems", "political", "politics", "portfolio",
    "poverty porn", "power", "pravasi bharatiya divas", "premium", "prescient",
    "preservation", "print", "priorities", "privilege", "process", "productivity",
    "professor", "prosocial", "psychology", "psychotherapy", "purpose", "python",
    "qualitative research", "quick thought", "quotes", "rape", "rca grad project",
    "reach out", "reading list", "reading", "recall", "reconstruccion", "reference note",
    "reflections", "reflective", "relationship", "remember", "request full text",
    "research area", "research papers", "research", "researcher", "researchers",
    "resources", "response", "resume", "rising strong", "rituals", "roland barthes",
    "rolling stone", "romantic love", "romantic relationship", "roots", "rosana simonassi",
    "running quotes", "safety", "sam altman", "scholarship", "science fiction",
    "sculpture", "second brain", "self awareness", "self esteem", "self help",
    "self reflection", "self worth", "self", "selfishness", "semiotics", "separation",
    "sex", "sexual attraction", "sexual assault", "sexual attraction", "shaan puri",
    "showreel", "side gigs", "sin", "skill", "skills", "skydiving", "smart city",
    "sop", "specialist", "stanford", "startup", "stoicism", "storytelling",
    "substack", "success", "sudan", "superflux", "surveillance", "survival",
    "taste", "technology", "the photographers gallery", "the script", "therapeutic recreation",
    "therapy", "tim ferriss", "tips", "to be edited", "touch designer", "traditions",
    "training", "trauma", "travel", "travelling", "tweets", "unconditional love",
    "university", "vanity", "vegetarian", "video", "viktor frankl", "visa",
    "vulnerability", "vulture", "warfare", "wealth", "web design", "website copy",
    "website", "wellbeing", "wieden+kennedy", "wife", "wishlist", "woman", "women",
    "work", "workshop", "worship", "writing", "youtube video", "zettelkasten"
];
