import type { LoomPreset, LoomSettings } from "../types";

export const DEFAULT_SETTINGS: LoomSettings = {
  text: "F",
  fontFamily: "Inconsolata",
  fontSize: 500,
  letterSpacing: 0,
  lineHeight: 1,
  align: "center",
  samplingMode: "fill",
  gridDensity: 27,
  spacingX: 1,
  spacingY: 1,
  gridOffsetX: 0,
  gridOffsetY: 0,
  coverageThreshold: 0.34,
  samplingResolution: 640,
  gridRotation: 0,
  gridType: "offset",
  moduleType: "woven",
  moduleWidth: 3,
  moduleHeight: 1,
  strokeWidth: 1,
  cornerRadius: 0,
  aspectRatio: 3,
  alternatingOrientation: true,
  overlap: 1.3,
  moduleRotation: 0,
  checkerFrequency: 2,
  parallelLines: 4,
  glyphWeight: 1,
  outlineWidth: 2,
  erosion: 0,
  expansion: 0,
  fidelity: 0.92,
  abstraction: 0.08,
  removalProbability: 0.02,
  randomness: 0.05,
  seed: 6214,
  noiseStrength: 0,
  noiseScale: 0.012,
  noiseOctaves: 2,
  directionalBias: 0,
  rotationVariance: 0,
  scaleVariance: 0.04,
  flowStrength: 0,
  playing: true,
  time: 0,
  animationMode: "wovenShift",
  speed: 1,
  loopDuration: 6,
  phase: 0,
  stagger: 0.4,
  staggerOrigin: "center",
  waveAmplitude: 12,
  wavelength: 300,
  easing: "easeInOut",
  posterFps: 60,
  motionBlur: 0,
  seamlessLoop: true,
  background: "#C4C3A4",
  primaryInk: "#000000",
  secondaryInk: "#363113",
  accent: "#D400A4",
  colorVariation: 0.08,
  invertPalette: false,
  palette: "fabric",
  layout: "fabric",
  canvasWidth: 1200,
  canvasHeight: 824,
  overUnder: "even",
  roundedEnds: false,
  originX: 0.5,
  originY: 0.5,
};

export const PRESETS: LoomPreset[] = [
  {
    name: "Reference Study",
    description: "Woven, pixel and line families arranged as a six-second fabric specimen.",
    settings: { ...DEFAULT_SETTINGS },
  },
  {
    name: "Quiet Grid",
    description: "A restrained black-and-paper square study.",
    settings: {
      layout: "square",
      moduleType: "square",
      gridType: "regular",
      gridDensity: 34,
      animationMode: "breathing",
      background: "#F1EFE6",
      primaryInk: "#161616",
      secondaryInk: "#666253",
      accent: "#161616",
      palette: "mono",
      text: "LOOM",
    },
  },
  {
    name: "Signal Field",
    description: "Hybrid modules pushed through a travelling directional wave.",
    settings: {
      layout: "motion",
      moduleType: "hybrid",
      gridType: "jittered",
      gridDensity: 38,
      randomness: 0.34,
      animationMode: "ripple",
      background: "#F0EFDA",
      primaryInk: "#111111",
      secondaryInk: "#314B3D",
      accent: "#F04A24",
      palette: "signal",
      text: "TYPE",
    },
  },
  {
    name: "Night Weave",
    description: "Fine luminous bundles flowing across a dark field.",
    settings: {
      layout: "fullscreen",
      moduleType: "lines",
      parallelLines: 5,
      gridType: "contour",
      gridDensity: 42,
      animationMode: "noiseDrift",
      noiseStrength: 14,
      background: "#10100E",
      primaryInk: "#F4F0D8",
      secondaryInk: "#9FAF92",
      accent: "#FF4DB8",
      palette: "night",
      text: "G",
    },
  },
];

export const PALETTES: Record<LoomSettings["palette"], Pick<LoomSettings, "background" | "primaryInk" | "secondaryInk" | "accent">> = {
  fabric: { background: "#C4C3A4", primaryInk: "#000000", secondaryInk: "#363113", accent: "#D400A4" },
  mono: { background: "#F1EFE6", primaryInk: "#161616", secondaryInk: "#777368", accent: "#161616" },
  signal: { background: "#F0EFDA", primaryInk: "#111111", secondaryInk: "#314B3D", accent: "#F04A24" },
  night: { background: "#10100E", primaryInk: "#F4F0D8", secondaryInk: "#9FAF92", accent: "#FF4DB8" },
};

