-- Runtime design tokens for Creator Studio → Design Studio.
-- Public visitors can read the published palette; only admins may change it.

create table if not exists public.design_system_settings (
  id text primary key default 'global' check (id = 'global'),
  draft_tokens jsonb not null default '{}'::jsonb,
  published_tokens jsonb not null default '{}'::jsonb,
  published_version bigint not null default 1,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  published_at timestamptz not null default now()
);

create table if not exists public.design_system_versions (
  id bigint generated by default as identity primary key,
  version bigint not null unique,
  tokens jsonb not null,
  published_by uuid references auth.users(id) on delete set null,
  published_at timestamptz not null default now()
);

alter table public.design_system_settings enable row level security;
alter table public.design_system_versions enable row level security;

drop policy if exists "Public read published design settings" on public.design_system_settings;
create policy "Public read published design settings"
  on public.design_system_settings for select
  using (true);

drop policy if exists "Admins manage design settings" on public.design_system_settings;
create policy "Admins manage design settings"
  on public.design_system_settings for all
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  )
  with check (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

drop policy if exists "Admins read design history" on public.design_system_versions;
create policy "Admins read design history"
  on public.design_system_versions for select
  using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );

create or replace function public.set_design_system_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists design_system_settings_updated_at on public.design_system_settings;
create trigger design_system_settings_updated_at
  before update on public.design_system_settings
  for each row execute function public.set_design_system_updated_at();

create or replace function public.capture_design_system_version()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' or new.published_tokens is distinct from old.published_tokens then
    insert into public.design_system_versions (version, tokens, published_by, published_at)
    values (new.published_version, new.published_tokens, new.updated_by, new.published_at)
    on conflict (version) do nothing;
  end if;
  return new;
end;
$$;

drop trigger if exists capture_design_system_version on public.design_system_settings;
create trigger capture_design_system_version
  after insert or update of published_tokens on public.design_system_settings
  for each row execute function public.capture_design_system_version();

insert into public.design_system_settings (
  id,
  draft_tokens,
  published_tokens,
  published_version
)
values (
  'global',
  '{
    "--pop-blue":"#2444ca","--pop-pink":"#ff7eb5","--pop-yellow":"#ffe44f","--pop-lime":"#caff48","--pop-orange":"#ff875c","--pop-purple":"#5524c7","--pop-cyan":"#62e6ff","--pop-cream":"#fff8e8","--pop-white":"#ffffff","--pop-ink":"#15130f",
    "--dark-page-bg":"#040404","--dark-surface-bg":"#0a0a0a","--dark-text-primary":"#f8fafc","--light-page-bg":"#f8fafc","--light-surface-bg":"#ffffff","--light-text-primary":"#0f172a",
    "--ds-display-min":"3","--ds-display-fluid":"6.7","--ds-display-max":"7","--ds-display-weight":"620","--ds-display-line":"0.9","--ds-display-track":"-0.065",
    "--ds-page-title-min":"2.5","--ds-page-title-fluid":"4.8","--ds-page-title-max":"5","--ds-page-title-weight":"620","--ds-page-title-line":"0.98","--ds-page-title-track":"-0.05",
    "--ds-section-title-min":"2.4","--ds-section-title-fluid":"4","--ds-section-title-max":"4","--ds-section-title-weight":"620","--ds-section-title-line":"0.98","--ds-section-title-track":"-0.05",
    "--ds-card-title-min":"1.4","--ds-card-title-fluid":"2.2","--ds-card-title-max":"1.9","--ds-card-title-weight":"720","--ds-card-title-line":"1.15","--ds-card-title-track":"-0.04",
    "--ds-body-min":"0.94","--ds-body-fluid":"1.12","--ds-body-max":"1.1","--ds-body-weight":"450","--ds-body-line":"1.5","--ds-body-track":"0",
    "--ds-reading-min":"1.05","--ds-reading-fluid":"1.45","--ds-reading-max":"1.35","--ds-reading-weight":"450","--ds-reading-line":"1.6","--ds-reading-track":"0",
    "--ds-label-size":"0.72","--ds-label-weight":"750","--ds-label-line":"1.35","--ds-label-track":"0.08",
    "--ds-grid-gap":"8","--ds-gutter-min":"16","--ds-gutter-fluid":"3","--ds-gutter-max":"56","--ds-section-block-min":"64","--ds-section-block-fluid":"6.5","--ds-section-block-max":"112","--ds-radius-panel":"24","--ds-radius-card":"18","--ds-radius-control":"14","--ds-radius-media":"14","--ds-card-inset":"10"
  }'::jsonb,
  '{
    "--pop-blue":"#2444ca","--pop-pink":"#ff7eb5","--pop-yellow":"#ffe44f","--pop-lime":"#caff48","--pop-orange":"#ff875c","--pop-purple":"#5524c7","--pop-cyan":"#62e6ff","--pop-cream":"#fff8e8","--pop-white":"#ffffff","--pop-ink":"#15130f",
    "--dark-page-bg":"#040404","--dark-surface-bg":"#0a0a0a","--dark-text-primary":"#f8fafc","--light-page-bg":"#f8fafc","--light-surface-bg":"#ffffff","--light-text-primary":"#0f172a",
    "--ds-display-min":"3","--ds-display-fluid":"6.7","--ds-display-max":"7","--ds-display-weight":"620","--ds-display-line":"0.9","--ds-display-track":"-0.065",
    "--ds-page-title-min":"2.5","--ds-page-title-fluid":"4.8","--ds-page-title-max":"5","--ds-page-title-weight":"620","--ds-page-title-line":"0.98","--ds-page-title-track":"-0.05",
    "--ds-section-title-min":"2.4","--ds-section-title-fluid":"4","--ds-section-title-max":"4","--ds-section-title-weight":"620","--ds-section-title-line":"0.98","--ds-section-title-track":"-0.05",
    "--ds-card-title-min":"1.4","--ds-card-title-fluid":"2.2","--ds-card-title-max":"1.9","--ds-card-title-weight":"720","--ds-card-title-line":"1.15","--ds-card-title-track":"-0.04",
    "--ds-body-min":"0.94","--ds-body-fluid":"1.12","--ds-body-max":"1.1","--ds-body-weight":"450","--ds-body-line":"1.5","--ds-body-track":"0",
    "--ds-reading-min":"1.05","--ds-reading-fluid":"1.45","--ds-reading-max":"1.35","--ds-reading-weight":"450","--ds-reading-line":"1.6","--ds-reading-track":"0",
    "--ds-label-size":"0.72","--ds-label-weight":"750","--ds-label-line":"1.35","--ds-label-track":"0.08",
    "--ds-grid-gap":"8","--ds-gutter-min":"16","--ds-gutter-fluid":"3","--ds-gutter-max":"56","--ds-section-block-min":"64","--ds-section-block-fluid":"6.5","--ds-section-block-max":"112","--ds-radius-panel":"24","--ds-radius-card":"18","--ds-radius-control":"14","--ds-radius-media":"14","--ds-card-inset":"10"
  }'::jsonb,
  1
)
on conflict (id) do nothing;

notify pgrst, 'reload schema';
